name: Deploy Shiny App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: shellai-runner-private-tst

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set locale
        run: |
         sudo apt-get update
         sudo apt-get install -y locales
         sudo dpkg-reconfigure locales
         sudo locale-gen en_US.UTF-8
         sudo update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8
         echo "LC_ALL=en_US.UTF-8" >> $GITHUB_ENV
         echo "LANG=en_US.UTF-8" >> $GITHUB_ENV 
      
      - uses: actions/cache@v2
        with:
         path: ${{ env.R_LIBS_USER }}
         key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
         restore-keys: |
             ${{ runner.os }}-r-
       
      - uses: sede-open/rlibcode-action/setup-r@v2-branch
      - name: Install dependencies
        run: |
         sudo apt-get update
         sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
         sudo apt-get install -y jq
         Rscript -e "install.packages('shiny')"
         Rscript -e "install.packages('rsconnect')"
          
  

      - name: Create manifest.json
        run: |
           chmod +x ./create-manifest.R 
           Rscript ./create-manifest.R


      - name: Deploy Shiny app
        run: Rscript ./deploy-app.R
        env:
          CONNECT_SERVER: ${{ secrets.CONNECT_SERVER }}
          CONNECT_API_KEY: ${{ secrets.CONNECT_API_KEY }}