name: Run Terraform with OpenID Connect
on: 
  push:
    branches:
     - main
  pull_request:
    branches:
     - main
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
      pull-requests: write
      
jobs: 
  analysis:
    if: github.event_name  == 'push'
    defaults:
      run:
        working-directory: terraform-example-deploy
    name: Analyse the Terraform
    environment: dev
    runs-on: ubuntu-latest
    env:
      TF_VAR_subscription_id: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      TF_VAR_tenant_id:  "${{ secrets.AZURE_TENANT_ID }}"
      TF_VAR_client_id: "${{ secrets.AZURE_CLIENT_ID }}"
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2.5.0

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3

    - name: Terraform Fmt
      run: terraform fmt -check

    - name: Terraform Init
      run: |
        terraform init \
        -backend-config="resource_group_name=${{secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME}}" \
        -backend-config="storage_account_name=${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME}}" \
        -backend-config="container_name=${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME}}"
        
    - name: Terraform Validate
      run: terraform validate -no-color
    - name: Terraform Plan
      run: |
       terraform plan 

     
   
    - name: Terrafrom apply
      run: terraform apply -auto-approve
